---

- name: For Debian-based
  block:  ### Deb-based ####

    - name: "install nginx"
      apt:
       pkg: [nginx]
      become: yes

    - name: "Create dir for websites"
      file:
       path: /var/www/{{ item }}
       state: directory
      become: yes
      with_items: "{{ siteslist }}"

    - name: "Create nginx config files"
      template: 
            src: website.j2
            dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
      with_items: "{{ siteslist }}"
      become: yes
      notify: nginxrestart
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: For RPM-based
  block: ##### RPM-based ########
    - name: "install EPEL"
      yum:
        pkg: [epel-release]
      become: yes

    - name: "install nginx"
      yum:
       pkg: [nginx]
      become: yes

    - name: "Create dir for websites"
      file:
       path: /var/www/{{ item }}
       state: directory
      become: yes
      with_items: "{{ siteslist }}"

    - name: "Create nginx config files"
      template: 
            src: website.j2
            dest: "/etc/nginx/conf.d/{{ item }}.conf"
      with_items: "{{ siteslist }}"
      become: yes
      notify: nginxrestart
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
